spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1111
    driver-class-name: org.h2.Driver
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  output:
    ansi:
      enabled: always
server:
  port: 8080
---
spring:
  profiles:
    active: default
logging:
  level:
    root: info

