spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://www.sungbae.net:9092/~/test
    username: sa
    password: test
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  output:
    ansi:
      enabled: always
server:
  port: 80
---
spring:
  profiles:
    active: default
logging:
  level:
    root: info

