CREATE SEQUENCE SHORT_URL_SEQ START WITH 1000000 MAXVALUE 218340105584895;

CREATE TABLE SHORT_URL (
                           SEQUENCE BIGINT DEFAULT SHORT_URL_SEQ.NEXTVAL PRIMARY KEY,
                           ORIGINAL_URL VARCHAR(4000) NOT NULL UNIQUE,
                           ORIGINAL_URL_HASH VARCHAR(50) NOT NULL UNIQUE,
                           REGISTRATION_DATE_TIME TIMESTAMP
);

CREATE INDEX ORIGINAL_URL_UNIQUE ON SHORT_URL(ORIGINAL_URL_HASH);
