package com.paktitucci.shorturl.convert.service;


import com.google.common.base.Charsets;
import com.google.common.hash.Hashing;
import com.paktitucci.shorturl.converter.UrlConverter;
import com.paktitucci.shorturl.dto.ShortUrlParam;
import com.paktitucci.shorturl.entity.ShortUrlEntity;
import com.paktitucci.shorturl.service.ShortUrlService;
import com.paktitucci.shorturl.service.UrlCheckService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.transaction.annotation.Transactional;

import static org.hamcrest.Matchers.is;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThat;


@RunWith(SpringRunner.class)
@SpringBootTest
public class UrlConvertServiceTest {

    @Autowired
    private UrlConverter shortUrlConverter;

    @Autowired
    private UrlConverter originalUrlConverter;

    @Autowired
    private ShortUrlService shortUrlService;

    @Autowired
    private UrlCheckService urlCheckService;

    /**
     * 새 Shortening URL 생성 테스트.
     */
    @Test
    @Transactional
    public void newShortUrlEntitySaveTest() {
        String originalUrl ="https://stackoverflow.com/";
        String originalUrlHash = Hashing.sha1().hashString(originalUrl, Charsets.UTF_8).toString();

        ShortUrlEntity entity = ShortUrlEntity.builder()
                                                   .originalUrl(originalUrl)
                                                   .originalUrlHash(originalUrlHash)
                                                   .isGeneratedNewShortUrl(Boolean.TRUE)
                                                   .build();
        ShortUrlEntity result = shortUrlService.saveShortUrl(entity);

        Assert.assertNotEquals(result.getSequence(), Long.valueOf(0));

    }

    /**
     * 이미 존재하는 Shortening URL인지 조회하는 테스트.(존재하지 않는 것을 테스트)
     */
    @Test
    public void existsShortUrlTest() {
        ShortUrlEntity result = urlCheckService.getShortUrlIfExists("6f86b88c9b0c752c1afab3bfabd3bd1b9a14129d");
        Assert.assertNotEquals(result, null);
    }

    /**
     * 이미 존재하는 Shortening URL인지 조회하는 테스트.(존재하는 것 테스트)
     */
    @Test
    public void alreadyExistsShortUrlTest() {
        String url = "https://www.daum.net";
        ShortUrlEntity convert = shortUrlConverter.convert(ShortUrlParam.of(url));
        assertThat(convert.getShortUrl(), is("emkC"));
    }

    /**
     * sequence를 이용해 Shortening URL을 조회하는 테스트.
     */
    @Test
    public void getShortEntityBySequenceTest() {
        ShortUrlEntity result = shortUrlService.getShortUrlEntityBySequence(999999L);
        assertEquals(result, null);
    }


    /**
     * 새 Shortening URL 생성 테스트.
     */
    @Test
    @Transactional
    public void generateNewShortUrlTest() {
        String url = "https://stackoverflow.com/questions/12626502/rollback-transaction-after-test";
        ShortUrlEntity convert = shortUrlConverter.convert(ShortUrlParam.of(url));
        assertThat(convert.isGeneratedNewShortUrl(), is(Boolean.TRUE));
    }

    /**
     * Shortening URL을 Original URL로 변환하는 테스트.
     */
    @Test
    public void shortUrlToOriginalTest() {
        String url = "http://localhost/emkC";
        ShortUrlEntity convert = originalUrlConverter.convert(ShortUrlParam.of(url));
        assertThat(convert.getOriginalUrl(), is("https://www.daum.net"));
    }

    /**
     * SHA-1로 암호화(인코딩)하는 테스트.
     */
    @Test
    public void sha1Test() {
        String url ="https://www.naver.com";
        String originalUrlHash = Hashing.sha1().hashString(url, Charsets.UTF_8).toString();
        Assert.assertEquals("118707c124d9597f63ddf00155afef055384017d", originalUrlHash);
    }

    /**
     * 긴 문자열(12348 bytes)를 SHA-1 알고리즘으로 인코딩했을 때에도 40 bytes 가 나오는지 테스트.
     */
    @Test
    public void longLengthCharSha1Test() {
        String url ="http://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhflhttp://www.marcusmiller.com?dlfasldkfjaldfjasldfjaskldfjlsadkfjlksadjfaldskjflkadjflakdfjladjflkaflasdkfjlaksdfjlakdjflkasdjflajdflkajdflkadlfakjdflajdflaksdjflaksjdflaksdjflaksdjflaskdjflaksdjfladjflasdjflasdkfjalkdfjlakdfjlaskdfjlasdkfjlaksdfjlaskdfjladkjflaksfjdlaskdjflakjdflakdjflasdfjlaksdfjlafjlaskdfjladfjlaskdfjlasdkfjladskjflkadjflakdfjlkdafjladfjlkadsfjlkasdfjlasdkfjlasdkfjlsadkjflsadfjlaksdfjlsadkfjalskdfjalsdkfjlsadkfjlasdkfjalksdfjalskdfjalsdfjasdlkfjalksdfjalsdkfjlaksdfjlksadjflksadfjlasdkfjlaskfjalsdkjfklajfsdalkfjfahdkjfahdfkahdfaidfhaduhfasiofuhdfouahdfoauhdfioqheufhdlsfjhalfdkjahdflhqoeiurhldskjhaflkjhalkdjfhqoiuerhlflasjfhlakdfjhalkdfjhalkdfjhieuhqdlfjkhaldkfjhasdlfkjhadlfjhoiqwryquilherlqehljkdhsflkjadhflkadjfhladkfjhladkfjhasldfkjahdlfjakhdfklajhdfqiuehilquhdfljahdsflkjadshfqieurhqliweufljfhaldfkajhdflkasjdhflakjdfhlakdfjhasdlkfjhasdlkfjhasdlfkjahsdflkjasdhflkasdjhflasdkjfhaslkdjfhasdlkfjhqweiuorhfqlieuhflkqdfjhlkajfdhlsakjfhasldkfjhaksdlfaslhdjkfhwqeiruyqweilfhslakdfjhaslkfjhhqiewufhqiouwelhfl";
        String originalUrlHash = Hashing.sha1().hashString(url, Charsets.UTF_8).toString();
        Assert.assertEquals(40, originalUrlHash.getBytes().length);
    }


}
